### PR TITLE
Upgrade to v1.0.0

### PR DESCRIPTION
**Pull request by stilic**
## Problem

- v1.0.0 of Flarum is released and I want to make this app migrate to this version.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by stilic** [comment]
I see the following when trying to install deps:
```
Info : DEBUG - ++ phpversion=7.3
Info : DEBUG - ++ COMPOSER_HOME=/var/www/flarum__2/.composer
Info : DEBUG - ++ php7.3 /var/www/flarum__2/composer.phar require 'flarum/core:~0.1.0-beta.16' --prefer-lowest --no-update -d /var/www/flarum__2 --quiet --no-interaction
Info : DEBUG - + ynh_exec_warn_less ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 '--commands="require' 'tituspijean/flarum-ext-auth-ldap:~0.1.0-beta.16-1' '--no-update"'
Info : DEBUG - + eval ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 '--commands="require' 'tituspijean/flarum-ext-auth-ldap:~0.1.0-beta.16-1' '--no-update"'
Info : DEBUG - ++ ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 '--commands=require tituspijean/flarum-ext-auth-ldap:~0.1.0-beta.16-1 --no-update'
Info : DEBUG - ++ declare -Ar args_array
Info : DEBUG - ++ workdir=/var/www/flarum__2
Info : DEBUG - ++ phpversion=7.3
Info : DEBUG - ++ COMPOSER_HOME=/var/www/flarum__2/.composer
Info : DEBUG - ++ php7.3 /var/www/flarum__2/composer.phar require 'tituspijean/flarum-ext-auth-ldap:~0.1.0-beta.16-1' --no-update -d /var/www/flarum__2 --quiet --no-interaction
Info : DEBUG - + ynh_exec_warn_less ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 '--commands="update"'
Info : DEBUG - + eval ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 '--commands="update"'
Info : DEBUG - ++ ynh_composer_exec --phpversion=7.3 --workdir=/var/www/flarum__2 --commands=update
Info : DEBUG - ++ declare -Ar args_array
Info : DEBUG - ++ workdir=/var/www/flarum__2
Info : DEBUG - ++ phpversion=7.3
Info : DEBUG - ++ COMPOSER_HOME=/var/www/flarum__2/.composer
Info : DEBUG - ++ php7.3 /var/www/flarum__2/composer.phar update -d /var/www/flarum__2 --quiet --no-interaction
Info : DEBUG - Your requirements could not be resolved to an installable set of packages.
Info : DEBUG - + ynh_exit_properly
```

**Comment by stilic** [comment]
!testme

**Comment by stilic** [comment]
!testme

**Comment by tituspijean** [comment]
Take a breath @Stylix58 :p The LDAP plugin needs to be updated for this version.

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
