### PR TITLE
Fix ynh_composer_exec syntax and upgrade to v1.1.1

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

. c.f. https://forum.yunohost.org/t/app-flarum-installation-echouee-une-erreur-est-survenue-dans-le-script-dinstallation-de-lapplication/17738

## Solution

- Issue is probably related to the fact that ynh_exec_* was doing an eval and doesn't anymore ...

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by tituspijean** [comment]
I am wondering what the heck I was thinking when I put those backslashes. 🔔

**Comment by alexAubin** [comment]
The backslashes were legit because of the way the ynh_exec_* works / related to the eval thingy ... Basically the command was interpreted **two times** so any special char had to be escape ... Except in some cases (like password with special chars they werent making everything explode), etc ...

Anyway that's fixed now but there are a few tricky unexpected edge case such as this one ...

**Comment by alexAubin** [comment]
Annnnnnd it's miserably failing because CI is still in 4.2

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/69)
[](https://ci.pijean.ovh/ci/job/69)

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/70)
[](https://ci.pijean.ovh/ci/job/70)

**Pull request merged**
