### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Get ride of sury*

## Solution
- *Apply last example_ynh*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/flarum_ynh%20PR145%20(yalh76)/)  => mkdir(): Disk quota exceeded in /var/www/flarum/vendor/illuminate/filesystem/Filesystem.php on line 466

Own CI Results for Revision: f4fc0d37834800985565ebcdf71cc69179e5df81 

### Stretch
image

### Buster
image

### CODE REVIEW

**Comment by tituspijean** [comment]
It seems your builds are facing the same memory issues as in #141. I have been stuck with those for months, and I cannot continue maintaining Flarum due to them.

**Comment by yalh76** [comment]
> 
> 
> It seems your builds are facing the same memory issues as in #141. I have been stuck with those for months, and I cannot continue maintaining Flarum due to them.

When you speaks abut memory issue, you speak of that erro:
```
Warning: yunohost.hook <lambda> - [1025.1] PHP Warning:  file_put_contents(): Only 0 of 533 bytes written, possibly out of free disk space in /var/www/flarum/vendor/flarum/core/src/Install/Steps/StoreConfig.php on line 45
Warning: yunohost.hook <lambda> - [1025.1] PHP Warning:  mkdir(): Disk quota exceeded in /var/www/flarum/vendor/illuminate/filesystem/Filesystem.php on line 466
Warning: yunohost.hook <lambda> - [1025.1] PHP Warning:  copy(/var/www/flarum/public/assets/fonts/fa-regular-400.eot): failed to open stream: No such file or directory in /var/www/flarum/vendor/illuminate/filesystem/Filesystem.php on line 239
```

**Comment by yalh76** [comment]
package_check working fine on my own CI.
Seems like a limitation from ci-apps-dev, due to quotas

**Review by tituspijean — APPROVED** [review]
Seems all good to me, thanks a lot!

**Pull request merged**
