### PR TITLE
Fix sign for string comparison.

### PR DESCRIPTION
**Pull request by frju365**
fixes https://github.com/YunoHost-Apps/flarum_ynh/issues/94
(normally)

### CODE REVIEW

**Comment by frju365** [comment]
Well, you idea of dpkg comparison was good too... Don't know what is the best for instance.

**Comment by tituspijean** [comment]
(Should have assigned myself, I definitely have some bad practices)

**Comment by frju365** [comment]
Yes, don't worry. I delete the branch. If you need help, don't hesitate ;)

**Comment by tituspijean** [comment]
You can find my proposal there #98.

**Pull request closed without merging**
