### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by tituspijean**

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
@tituspijean why not let the user choose their password during the installation? This will avoid sending a temporary one by email ...

**Comment by tituspijean** [comment]
This random password is actually not necessary, thanks to the SSOwat extension. But you are right, maybe having the user set their own is better. Do not hesitate to request this change, I will look into it.

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Pull request merged**
